# Generated by Django 5.0.2 on 2024-02-14 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_sem', models.IntegerField()),
                ('completed_sem', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('overall_status', models.TextField()),
                ('attendance_perc', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='acad_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academics', to='login.academics'),
        ),
    ]
