# Generated by Django 5.0.3 on 2024-03-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_admin_calender_class_course_department_holiday_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Attendance Report',
            },
        ),
    ]
