# Generated by Django 5.0.3 on 2024-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='dob',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='faculty',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
