# Generated by Django 5.0.3 on 2024-04-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_faculty_dob_faculty_email_faculty_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.IntegerField(default=1),
        ),
    ]
