# Generated by Django 5.0.3 on 2024-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_student_batch_teaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('vivamark', models.FloatField()),
                ('output', models.CharField(choices=[('Verified', 'Verified'), ('Not Verified', 'Not Verified')], max_length=12)),
                ('programname', models.CharField(max_length=100)),
            ],
        ),
    ]
