# Generated by Django 5.0.3 on 2024-04-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_coursediary_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.IntegerField(default=1),
        ),
    ]
