# Generated by Django 5.0.3 on 2024-04-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='sender_id',
            field=models.CharField(max_length=20),
        ),
    ]
